### PR TITLE
fix(pc): close #62, get scrollBarWidth and paddingRight first

### LINKED ISSUE #62: bug: Broken reversed scrollbar on desktop
**Version**
Version 1.3.0

**Describe the bug**
After updating to 1.3.0 `padding-right` on `html` gets set to 0 on desktop.

Providing a reproduction demo will be better (you can pick a platform below and **fork** the demo):
* codepen: https://codepen.io/kyrylo-soulandwolf/pen/MWzQYwK

**Expected behaviour**
Padding is to be set on `html` to reverse the width of the scroll bar.

### PR DESCRIPTION
**Pull request by BuptStEve**
**Summary**

add demos and fix #62

**What kind of change does this PR introduce?** (check at least one)

- [x] Bug fix
- [x] Docs

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following platforms:

- [x] PC
- [x] iOS
- [x] Android

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -21,10 +21,12 @@ const supportsNativeSmoothScroll = !isServer() && 'scrollBehavior' in document.d
 const setOverflowHiddenPc = () => {
   const $html = document.documentElement
   const htmlStyle = { ...$html.style }
+  const scrollBarWidth = window.innerWidth - $html.clientWidth
+  const previousPaddingRight = parseInt(window.getComputedStyle($html).paddingRight, 10)
```
Comment (BuptStEve) [inline src/index.ts:25]: we should do these before overflow hidden
